version: "3.5"
services:
  immich-server:
    build:
      context: ./immich-server
      args:
        IMMICH_VERSION: release
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE_NAME: "immich"
      UPLOAD_LOCATION: "./library"
    volumes:
      - immich-server-upload:/data
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    ports:
      - "2283:2283"
  immich-machine-learning:
    build:
      context: ./immich-machine-learning
      args:
        IMMICH_VERSION: release
    environment:
      UPLOAD_LOCATION: "./library"
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false
  redis:
    build:
      context: ./redis
      args:
        VALKEY_VERSION: 8-bookworm
    environment: {}
    volumes:
      - redis-data:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    build:
      context: ./postgres
      args:
        POSTGRES_VERSION: 14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "immich"
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_DATA_LOCATION: "./postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  immich-server-upload: {}
  model-cache: {}
  redis-data: {}
  postgres-data: {}
